package lsf.zuba.javacc;

/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SyntaxCheckerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Chart_type = 21;
  /** RegularExpression Id. */
  int Db_type = 22;
  /** RegularExpression Id. */
  int Axis_type = 23;
  /** RegularExpression Id. */
  int String = 24;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ML_COMMENT_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
    "<token of kind 7>",
    "\"DRAW\"",
    "\"CHART\"",
    "\"FOR\"",
    "\"WHICH\"",
    "\"TO\"",
    "\"INCLUDING\"",
    "\"X\"",
    "\"Y\"",
    "\"Y2\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\":\"",
    "<Chart_type>",
    "<Db_type>",
    "<Axis_type>",
    "<String>",
    "\"(\"",
    "\")\"",
  };

}
